name: Mi primera Integracion Continua

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v2
      - name: Instalar JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Construior con maven
        run: |
          mvn clean package -DskipTests
          ls target/
      - name: Guardar paquete .jar para despues desplegar
        uses: actions/upload-artifact@v4
        with:
          name: moviecards-java
          path: "${{ github.workspace }}/target/*.jar"

  test:
    
    runs-on: ubuntu-latest
    steps:
      -  name: pruebas
         run: echo "pruebas"






  qa: 
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: calidad
        run: echo "calidad"

  deploy:
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - name: despliegue
        run: echo "despliegue"








    

