name: Mi primera Integracion Continua

on: push

jobs:

  compilar:
    runs-on: ubuntu-latest
    steps:
      - name: empaquetado
        run: echo "empaquetado"

  probar:
    needs: compilar
    runs-on: ubuntu-latest
    steps:
      -  name: pruebas
         run: echo "pruebas"


  controlar_calidad: 
    needs: probar
    runs-on: ubuntu-latest
    step:
      - name: calidad
        run: echo "calidad"

  desplegar:
    needs: controlar_calidad
    runs-on: ubuntu-latest
    steps:
      - name: despliegue
        run: echo "despliegue"








    

